bubjungdong:
	python -m uvicorn bubjungdong:app --host 0.0.0.0 --port 5000 --reload

apartment:
	python -m uvicorn apartment:app --host 0.0.0.0 --port 5001 --reload

excluusear:
	python -m uvicorn excluusear:app --host 0.0.0.0 --port 5002 --reload
