# Base Image
FROM ubuntu:latest

# RUN Command
RUN echo Hello~ Its Shell Type command.
RUN ["echo", "Hello~ Its Exec Type Command."]
Run ["/bin/bash", "-c", "echo 'Hello~ Its /bin/bash execution in Shell Type Command.'"]
